add 10.3 and fix sync mdbci job

diff --git a/maxscale_jobs/include/sync_repositories_on_nodes/run_git_command_shell.yaml b/maxscale_jobs/include/sync_repositories_on_nodes/run_git_command_shell.yaml
--- a/maxscale_jobs/include/sync_repositories_on_nodes/run_git_command_shell.yaml
+++ b/maxscale_jobs/include/sync_repositories_on_nodes/run_git_command_shell.yaml
@@ -1,19 +1,9 @@
 shell: |
   cd "$path_to_repository"
   git fetch -a
-  if [ "$source" == "BRANCH" ] ; then
-    git reset --hard
-    git checkout $value
-    git pull --no-edit origin $value
-    if [ $? -ne 0 ] ; then
-      echo "Error checkout branch $value"
-      exit 1
-    fi
-  fi
-
-  if [ "$source" == "COMMIT"  ] || [ "$source" == "TAG" ]; then
-    if ! git reset --hard $value; then
-      echo "Error reset to tag $value of resetting tree to the commit $value"
-      exit 1
-    fi
+  git checkout $source
+  git pull --no-edit origin $source
+  if [ $? -ne 0 ] ; then
+    echo "Error checkout branch $source"
+    exit 1
   fi
