#7496 refactored

diff --git a/maxscale_jobs/validate_yaml_by_pushes.yaml b/maxscale_jobs/validate_yaml_by_pushes.yaml
--- a/maxscale_jobs/validate_yaml_by_pushes.yaml
+++ b/maxscale_jobs/validate_yaml_by_pushes.yaml
@@ -1,5 +1,5 @@
 - job:
-    name: validate_yaml_by_pushes
+    name: kaluzny_test_job
     description: 'This job check maxscale-jobs repo content using validator triggered by pushes.'
     triggers:
       - github
@@ -12,6 +12,10 @@
       - shell: |
           prop_file="failed_yaml_tests_property_file"
           injection_var="FAILED_YAML_TESTS_LIST"
+
+          if [ -f "$prop_file" ]; then
+              rm "$prop_file"
+          fi
 
           jobs=`ls maxscale_jobs/*.yaml -1`
           res=0
@@ -38,13 +42,21 @@
             echo -e $failed_list
           fi
 
-          prop_file_content=$(cat "$prop_file")
+          prop_file_content=$(cat "$prop_file") || true
           if [[ -n "$prop_file_content" ]]; then
-            echo "$injection_var=Failed yaml jobs: \\$prop_file_content" > "$prop_file"
+            echo "$injection_var=Failed yaml jobs: \\" > "$prop_file"
+            echo "$prop_file_content" >> "$prop_file"
+          else
+            echo "$injection_var=All jobs are valid" >> "$prop_file"
           fi
-
-          exit $res
       - inject:
           properties-file: failed_yaml_tests_property_file
+      - shell: |
+          prop_file="failed_yaml_tests_property_file"
+          injection_var="FAILED_YAML_TESTS_LIST"
+
+          if [[ -z $(cat "$prop_file" | grep "All jobs are valid") ]]; then
+          	exit 1
+          fi
     publishers:
       - !include: './maxscale_jobs/include/mail_yaml.yaml'
